// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebVot.Data;

#nullable disable

namespace WebVot.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231206085008_webvot")]
    partial class webvot
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebVot.Models.DonHang", b =>
                {
                    b.Property<string>("MaDh")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaDH")
                        .IsFixedLength();

                    b.Property<string>("MaSp")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaSP")
                        .IsFixedLength();

                    b.Property<int?>("ThanhTien")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("username");

                    b.HasKey("MaDh")
                        .HasName("PK__DonHang__2725866194F3421C");

                    b.HasIndex(new[] { "MaSp" }, "IX_DonHang_MaSP");

                    b.HasIndex(new[] { "Username" }, "IX_DonHang_username");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("WebVot.Models.Ncc", b =>
                {
                    b.Property<string>("MaNcc")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaNCC")
                        .IsFixedLength();

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Sdt")
                        .HasColumnType("int")
                        .HasColumnName("sdt");

                    b.Property<string>("TenNcc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenNCC");

                    b.HasKey("MaNcc")
                        .HasName("PK__NCC__3A185DEB4FBFA0A0");

                    b.ToTable("NCC");
                });

            modelBuilder.Entity("WebVot.Models.Nsx", b =>
                {
                    b.Property<string>("MaNsx")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaNSX")
                        .IsFixedLength();

                    b.Property<string>("TenNsx")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenNSX");

                    b.HasKey("MaNsx")
                        .HasName("PK__NSX__3A1BDBD291331705");

                    b.ToTable("NSX");
                });

            modelBuilder.Entity("WebVot.Models.SanPham", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaSP")
                        .IsFixedLength();

                    b.Property<int>("GiaBan")
                        .HasColumnType("int");

                    b.Property<int?>("GiaGoc")
                        .HasColumnType("int");

                    b.Property<string>("Hinhanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNcc")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaNCC")
                        .IsFixedLength();

                    b.Property<string>("MaNsx")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MaNSX")
                        .IsFixedLength();

                    b.Property<int?>("Sluong")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp")
                        .HasName("pk_SanPham_MaSp");

                    b.HasIndex(new[] { "MaNcc" }, "IX_SanPham_MaNCC");

                    b.HasIndex(new[] { "MaNsx" }, "IX_SanPham_MaNSX");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("WebVot.Models.TaiKhoan", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("username");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("user_password");

                    b.HasKey("Username")
                        .HasName("pk_TaiKhoan_username");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("WebVot.Models.DonHang", b =>
                {
                    b.HasOne("WebVot.Models.SanPham", "MaSpNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("fk_donhang_sanpham");

                    b.HasOne("WebVot.Models.TaiKhoan", "UsernameNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("Username")
                        .IsRequired()
                        .HasConstraintName("fk_donhang_taikhoan");

                    b.Navigation("MaSpNavigation");

                    b.Navigation("UsernameNavigation");
                });

            modelBuilder.Entity("WebVot.Models.SanPham", b =>
                {
                    b.HasOne("WebVot.Models.Ncc", "MaNccNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNcc")
                        .IsRequired()
                        .HasConstraintName("fk_sanpham_ncc");

                    b.HasOne("WebVot.Models.Nsx", "MaNsxNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNsx")
                        .IsRequired()
                        .HasConstraintName("fk_sanpham_nsx");

                    b.Navigation("MaNccNavigation");

                    b.Navigation("MaNsxNavigation");
                });

            modelBuilder.Entity("WebVot.Models.Ncc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebVot.Models.Nsx", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebVot.Models.SanPham", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebVot.Models.TaiKhoan", b =>
                {
                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
